name: flutter_rpg_audiodrama
description: "Uma plataforma para ADRPG"
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  http: ^1.3.0
  shared_preferences: ^2.4.0
  provider: ^6.1.2
  go_router: ^14.7.2
  cloud_firestore: ^5.6.2
  uuid: ^4.5.1
  badges: ^3.1.2
  lottie: ^3.3.1
  intl: ^0.19.0
  flutter_expandable_fab: ^2.3.0
  fl_chart: ^0.70.2
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.1
  file_picker: ^10.1.0
  string_similarity: ^2.1.1
  just_audio: ^0.9.46
  firebase_database: ^11.3.5
  logger: ^2.5.0
  material_design_icons_flutter: ^7.0.7296
  font_awesome_flutter: ^10.8.0
  flutter_fullscreen: ^1.2.0 
  flutter_native_splash: ^2.4.6
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/sheets/
    - assets/images/
    - assets/lotties/
    - sounds/rolls/
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/bungee.ttf
    - family: SourceSerif4
      fonts:
        - asset: assets/fonts/source_serif4.ttf
        - asset: assets/fonts/source_serif4-italic.ttf
          style: italic
  
flutter_launcher_icons:
    image_path: "assets/images/d20-0.png"
    android: "launcher_icon"
    min_sdk_android: 21
    ios: true
    remove_alpha_channel_ios: true  
    color: "#261918" 

flutter_native_splash:
  color: "#261918"  
  android_12:
    color: "#261918"
  android: true
  ios: false
  web: false

